/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutomationCondition
 */
export interface AutomationCondition {
    /**
     * 
     * @type {number}
     * @memberof AutomationCondition
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof AutomationCondition
     */
    automation_id: number;
    /**
     * 
     * @type {string}
     * @memberof AutomationCondition
     */
    condition_type: AutomationConditionConditionTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof AutomationCondition
     */
    device_id: number | null;
    /**
     * 
     * @type {string}
     * @memberof AutomationCondition
     */
    device_state: AutomationConditionDeviceStateEnum;
    /**
     * 
     * @type {number}
     * @memberof AutomationCondition
     */
    device_value: number | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AutomationCondition
     */
    device_extra_data: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof AutomationCondition
     */
    cron_expression: string | null;
}


/**
 * @export
 */
export const AutomationConditionConditionTypeEnum = {
    Device: 'device',
    Cron: 'cron'
} as const;
export type AutomationConditionConditionTypeEnum = typeof AutomationConditionConditionTypeEnum[keyof typeof AutomationConditionConditionTypeEnum];

/**
 * @export
 */
export const AutomationConditionDeviceStateEnum = {
    On: 'on',
    Off: 'off'
} as const;
export type AutomationConditionDeviceStateEnum = typeof AutomationConditionDeviceStateEnum[keyof typeof AutomationConditionDeviceStateEnum];


/**
 * Check if a given object implements the AutomationCondition interface.
 */
export function instanceOfAutomationCondition(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "automation_id" in value;
    isInstance = isInstance && "condition_type" in value;
    isInstance = isInstance && "device_id" in value;
    isInstance = isInstance && "device_state" in value;
    isInstance = isInstance && "device_value" in value;
    isInstance = isInstance && "device_extra_data" in value;
    isInstance = isInstance && "cron_expression" in value;

    return isInstance;
}

export function AutomationConditionFromJSON(json: any): AutomationCondition {
    return AutomationConditionFromJSONTyped(json, false);
}

export function AutomationConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutomationCondition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'automation_id': json['automation_id'],
        'condition_type': json['condition_type'],
        'device_id': json['device_id'],
        'device_state': json['device_state'],
        'device_value': json['device_value'],
        'device_extra_data': json['device_extra_data'],
        'cron_expression': json['cron_expression'],
    };
}

export function AutomationConditionToJSON(value?: AutomationCondition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'automation_id': value.automation_id,
        'condition_type': value.condition_type,
        'device_id': value.device_id,
        'device_state': value.device_state,
        'device_value': value.device_value,
        'device_extra_data': value.device_extra_data,
        'cron_expression': value.cron_expression,
    };
}

