/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAutomationRequest
 */
export interface CreateAutomationRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAutomationRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAutomationRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateAutomationRequest
     */
    logical_operator: CreateAutomationRequestLogicalOperatorEnum;
}


/**
 * @export
 */
export const CreateAutomationRequestLogicalOperatorEnum = {
    And: 'and',
    Or: 'or'
} as const;
export type CreateAutomationRequestLogicalOperatorEnum = typeof CreateAutomationRequestLogicalOperatorEnum[keyof typeof CreateAutomationRequestLogicalOperatorEnum];


/**
 * Check if a given object implements the CreateAutomationRequest interface.
 */
export function instanceOfCreateAutomationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "logical_operator" in value;

    return isInstance;
}

export function CreateAutomationRequestFromJSON(json: any): CreateAutomationRequest {
    return CreateAutomationRequestFromJSONTyped(json, false);
}

export function CreateAutomationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAutomationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'logical_operator': json['logical_operator'],
    };
}

export function CreateAutomationRequestToJSON(value?: CreateAutomationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'logical_operator': value.logical_operator,
    };
}

