/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner
 */
export interface GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner {
    /**
     * 
     * @type {number}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner
     */
    device_id: number;
    /**
     * 
     * @type {string}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner
     */
    device_name: string;
    /**
     * 
     * @type {string}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner
     */
    device_description_location: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner
     */
    device_category: GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerDeviceCategoryEnum;
    /**
     * 
     * @type {number}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner
     */
    on_duration: number;
    /**
     * 
     * @type {number}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner
     */
    watt_seconds: number;
    /**
     * 
     * @type {number}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner
     */
    activity_count: number;
}


/**
 * @export
 */
export const GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerDeviceCategoryEnum = {
    Light: 'light',
    Thermostat: 'thermostat',
    Door: 'door',
    AirConditioner: 'air_conditioner',
    Fan: 'fan'
} as const;
export type GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerDeviceCategoryEnum = typeof GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerDeviceCategoryEnum[keyof typeof GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerDeviceCategoryEnum];


/**
 * Check if a given object implements the GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner interface.
 */
export function instanceOfGetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "device_id" in value;
    isInstance = isInstance && "device_name" in value;
    isInstance = isInstance && "device_description_location" in value;
    isInstance = isInstance && "device_category" in value;
    isInstance = isInstance && "on_duration" in value;
    isInstance = isInstance && "watt_seconds" in value;
    isInstance = isInstance && "activity_count" in value;

    return isInstance;
}

export function GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerFromJSON(json: any): GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner {
    return GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerFromJSONTyped(json, false);
}

export function GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'device_id': json['device_id'],
        'device_name': json['device_name'],
        'device_description_location': json['device_description_location'],
        'device_category': json['device_category'],
        'on_duration': json['on_duration'],
        'watt_seconds': json['watt_seconds'],
        'activity_count': json['activity_count'],
    };
}

export function GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerToJSON(value?: GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'device_id': value.device_id,
        'device_name': value.device_name,
        'device_description_location': value.device_description_location,
        'device_category': value.device_category,
        'on_duration': value.on_duration,
        'watt_seconds': value.watt_seconds,
        'activity_count': value.activity_count,
    };
}

