/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner } from './GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner';
import {
    GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerFromJSON,
    GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerFromJSONTyped,
    GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerToJSON,
} from './GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner';

/**
 * 
 * @export
 * @interface GetAggregatedAnalytics200ResponseAggregatedAnalytics
 */
export interface GetAggregatedAnalytics200ResponseAggregatedAnalytics {
    /**
     * 
     * @type {number}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalytics
     */
    on_duration: number;
    /**
     * 
     * @type {number}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalytics
     */
    on_duration_compare: number;
    /**
     * 
     * @type {number}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalytics
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalytics
     */
    count_compare: number;
    /**
     * 
     * @type {number}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalytics
     */
    watt_seconds: number;
    /**
     * 
     * @type {number}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalytics
     */
    watt_seconds_compare: number;
    /**
     * 
     * @type {number}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalytics
     */
    activity_count: number;
    /**
     * 
     * @type {number}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalytics
     */
    activity_count_compare: number;
    /**
     * 
     * @type {Array<GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner>}
     * @memberof GetAggregatedAnalytics200ResponseAggregatedAnalytics
     */
    devices: Array<GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInner>;
}

/**
 * Check if a given object implements the GetAggregatedAnalytics200ResponseAggregatedAnalytics interface.
 */
export function instanceOfGetAggregatedAnalytics200ResponseAggregatedAnalytics(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "on_duration" in value;
    isInstance = isInstance && "on_duration_compare" in value;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "count_compare" in value;
    isInstance = isInstance && "watt_seconds" in value;
    isInstance = isInstance && "watt_seconds_compare" in value;
    isInstance = isInstance && "activity_count" in value;
    isInstance = isInstance && "activity_count_compare" in value;
    isInstance = isInstance && "devices" in value;

    return isInstance;
}

export function GetAggregatedAnalytics200ResponseAggregatedAnalyticsFromJSON(json: any): GetAggregatedAnalytics200ResponseAggregatedAnalytics {
    return GetAggregatedAnalytics200ResponseAggregatedAnalyticsFromJSONTyped(json, false);
}

export function GetAggregatedAnalytics200ResponseAggregatedAnalyticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAggregatedAnalytics200ResponseAggregatedAnalytics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'on_duration': json['on_duration'],
        'on_duration_compare': json['on_duration_compare'],
        'count': json['count'],
        'count_compare': json['count_compare'],
        'watt_seconds': json['watt_seconds'],
        'watt_seconds_compare': json['watt_seconds_compare'],
        'activity_count': json['activity_count'],
        'activity_count_compare': json['activity_count_compare'],
        'devices': ((json['devices'] as Array<any>).map(GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerFromJSON)),
    };
}

export function GetAggregatedAnalytics200ResponseAggregatedAnalyticsToJSON(value?: GetAggregatedAnalytics200ResponseAggregatedAnalytics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'on_duration': value.on_duration,
        'on_duration_compare': value.on_duration_compare,
        'count': value.count,
        'count_compare': value.count_compare,
        'watt_seconds': value.watt_seconds,
        'watt_seconds_compare': value.watt_seconds_compare,
        'activity_count': value.activity_count,
        'activity_count_compare': value.activity_count_compare,
        'devices': ((value.devices as Array<any>).map(GetAggregatedAnalytics200ResponseAggregatedAnalyticsDevicesInnerToJSON)),
    };
}

