/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Automation } from './Automation';
import {
    AutomationFromJSON,
    AutomationFromJSONTyped,
    AutomationToJSON,
} from './Automation';

/**
 * 
 * @export
 * @interface GetAutomations200Response
 */
export interface GetAutomations200Response {
    /**
     * 
     * @type {Array<Automation>}
     * @memberof GetAutomations200Response
     */
    automations: Array<Automation>;
}

/**
 * Check if a given object implements the GetAutomations200Response interface.
 */
export function instanceOfGetAutomations200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "automations" in value;

    return isInstance;
}

export function GetAutomations200ResponseFromJSON(json: any): GetAutomations200Response {
    return GetAutomations200ResponseFromJSONTyped(json, false);
}

export function GetAutomations200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAutomations200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'automations': ((json['automations'] as Array<any>).map(AutomationFromJSON)),
    };
}

export function GetAutomations200ResponseToJSON(value?: GetAutomations200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'automations': ((value.automations as Array<any>).map(AutomationToJSON)),
    };
}

