/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetAggregatedAnalytics200ResponseAggregatedAnalytics } from './GetAggregatedAnalytics200ResponseAggregatedAnalytics';
import {
    GetAggregatedAnalytics200ResponseAggregatedAnalyticsFromJSON,
    GetAggregatedAnalytics200ResponseAggregatedAnalyticsFromJSONTyped,
    GetAggregatedAnalytics200ResponseAggregatedAnalyticsToJSON,
} from './GetAggregatedAnalytics200ResponseAggregatedAnalytics';

/**
 * 
 * @export
 * @interface GetAggregatedAnalytics200Response
 */
export interface GetAggregatedAnalytics200Response {
    /**
     * 
     * @type {GetAggregatedAnalytics200ResponseAggregatedAnalytics}
     * @memberof GetAggregatedAnalytics200Response
     */
    aggregated_analytics: GetAggregatedAnalytics200ResponseAggregatedAnalytics;
}

/**
 * Check if a given object implements the GetAggregatedAnalytics200Response interface.
 */
export function instanceOfGetAggregatedAnalytics200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "aggregated_analytics" in value;

    return isInstance;
}

export function GetAggregatedAnalytics200ResponseFromJSON(json: any): GetAggregatedAnalytics200Response {
    return GetAggregatedAnalytics200ResponseFromJSONTyped(json, false);
}

export function GetAggregatedAnalytics200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAggregatedAnalytics200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aggregated_analytics': GetAggregatedAnalytics200ResponseAggregatedAnalyticsFromJSON(json['aggregated_analytics']),
    };
}

export function GetAggregatedAnalytics200ResponseToJSON(value?: GetAggregatedAnalytics200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aggregated_analytics': GetAggregatedAnalytics200ResponseAggregatedAnalyticsToJSON(value.aggregated_analytics),
    };
}

