/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCurrentUser200ResponseUser } from './GetCurrentUser200ResponseUser';
import {
    GetCurrentUser200ResponseUserFromJSON,
    GetCurrentUser200ResponseUserFromJSONTyped,
    GetCurrentUser200ResponseUserToJSON,
} from './GetCurrentUser200ResponseUser';

/**
 * 
 * @export
 * @interface GetCurrentUser200Response
 */
export interface GetCurrentUser200Response {
    /**
     * 
     * @type {GetCurrentUser200ResponseUser}
     * @memberof GetCurrentUser200Response
     */
    user: GetCurrentUser200ResponseUser | null;
}

/**
 * Check if a given object implements the GetCurrentUser200Response interface.
 */
export function instanceOfGetCurrentUser200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

export function GetCurrentUser200ResponseFromJSON(json: any): GetCurrentUser200Response {
    return GetCurrentUser200ResponseFromJSONTyped(json, false);
}

export function GetCurrentUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCurrentUser200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': GetCurrentUser200ResponseUserFromJSON(json['user']),
    };
}

export function GetCurrentUser200ResponseToJSON(value?: GetCurrentUser200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': GetCurrentUser200ResponseUserToJSON(value.user),
    };
}

