/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCurrentUser200ResponseUser
 */
export interface GetCurrentUser200ResponseUser {
    /**
     * 
     * @type {number}
     * @memberof GetCurrentUser200ResponseUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetCurrentUser200ResponseUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof GetCurrentUser200ResponseUser
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetCurrentUser200ResponseUser
     */
    image_url: string | null;
}

/**
 * Check if a given object implements the GetCurrentUser200ResponseUser interface.
 */
export function instanceOfGetCurrentUser200ResponseUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "image_url" in value;

    return isInstance;
}

export function GetCurrentUser200ResponseUserFromJSON(json: any): GetCurrentUser200ResponseUser {
    return GetCurrentUser200ResponseUserFromJSONTyped(json, false);
}

export function GetCurrentUser200ResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCurrentUser200ResponseUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'name': json['name'],
        'image_url': json['image_url'],
    };
}

export function GetCurrentUser200ResponseUserToJSON(value?: GetCurrentUser200ResponseUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'name': value.name,
        'image_url': value.image_url,
    };
}

