/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDevices200ResponseDevicesInner
 */
export interface GetDevices200ResponseDevicesInner {
    /**
     * 
     * @type {number}
     * @memberof GetDevices200ResponseDevicesInner
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof GetDevices200ResponseDevicesInner
     */
    user_id: number;
    /**
     * 
     * @type {string}
     * @memberof GetDevices200ResponseDevicesInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetDevices200ResponseDevicesInner
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof GetDevices200ResponseDevicesInner
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetDevices200ResponseDevicesInner
     */
    description_location: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetDevices200ResponseDevicesInner
     */
    device_category: GetDevices200ResponseDevicesInnerDeviceCategoryEnum;
    /**
     * 
     * @type {Date}
     * @memberof GetDevices200ResponseDevicesInner
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof GetDevices200ResponseDevicesInner
     */
    current_state: GetDevices200ResponseDevicesInnerCurrentStateEnum;
    /**
     * 
     * @type {number}
     * @memberof GetDevices200ResponseDevicesInner
     */
    current_value: number | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GetDevices200ResponseDevicesInner
     */
    current_extra_data: { [key: string]: any; } | null;
}


/**
 * @export
 */
export const GetDevices200ResponseDevicesInnerDeviceCategoryEnum = {
    Light: 'light',
    Thermostat: 'thermostat',
    Door: 'door',
    AirConditioner: 'air_conditioner',
    Fan: 'fan'
} as const;
export type GetDevices200ResponseDevicesInnerDeviceCategoryEnum = typeof GetDevices200ResponseDevicesInnerDeviceCategoryEnum[keyof typeof GetDevices200ResponseDevicesInnerDeviceCategoryEnum];

/**
 * @export
 */
export const GetDevices200ResponseDevicesInnerCurrentStateEnum = {
    On: 'on',
    Off: 'off'
} as const;
export type GetDevices200ResponseDevicesInnerCurrentStateEnum = typeof GetDevices200ResponseDevicesInnerCurrentStateEnum[keyof typeof GetDevices200ResponseDevicesInnerCurrentStateEnum];


/**
 * Check if a given object implements the GetDevices200ResponseDevicesInner interface.
 */
export function instanceOfGetDevices200ResponseDevicesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "user_id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "path" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "description_location" in value;
    isInstance = isInstance && "device_category" in value;
    isInstance = isInstance && "created_at" in value;
    isInstance = isInstance && "current_state" in value;
    isInstance = isInstance && "current_value" in value;
    isInstance = isInstance && "current_extra_data" in value;

    return isInstance;
}

export function GetDevices200ResponseDevicesInnerFromJSON(json: any): GetDevices200ResponseDevicesInner {
    return GetDevices200ResponseDevicesInnerFromJSONTyped(json, false);
}

export function GetDevices200ResponseDevicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDevices200ResponseDevicesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user_id': json['user_id'],
        'name': json['name'],
        'path': json['path'],
        'description': json['description'],
        'description_location': json['description_location'],
        'device_category': json['device_category'],
        'created_at': (new Date(json['created_at'])),
        'current_state': json['current_state'],
        'current_value': json['current_value'],
        'current_extra_data': json['current_extra_data'],
    };
}

export function GetDevices200ResponseDevicesInnerToJSON(value?: GetDevices200ResponseDevicesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'user_id': value.user_id,
        'name': value.name,
        'path': value.path,
        'description': value.description,
        'description_location': value.description_location,
        'device_category': value.device_category,
        'created_at': (value.created_at.toISOString()),
        'current_state': value.current_state,
        'current_value': value.current_value,
        'current_extra_data': value.current_extra_data,
    };
}

