/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDeviceActivities200ResponseDeviceActivitiesInnerDevice
 */
export interface GetDeviceActivities200ResponseDeviceActivitiesInnerDevice {
    /**
     * 
     * @type {string}
     * @memberof GetDeviceActivities200ResponseDeviceActivitiesInnerDevice
     */
    name: string;
}

/**
 * Check if a given object implements the GetDeviceActivities200ResponseDeviceActivitiesInnerDevice interface.
 */
export function instanceOfGetDeviceActivities200ResponseDeviceActivitiesInnerDevice(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function GetDeviceActivities200ResponseDeviceActivitiesInnerDeviceFromJSON(json: any): GetDeviceActivities200ResponseDeviceActivitiesInnerDevice {
    return GetDeviceActivities200ResponseDeviceActivitiesInnerDeviceFromJSONTyped(json, false);
}

export function GetDeviceActivities200ResponseDeviceActivitiesInnerDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDeviceActivities200ResponseDeviceActivitiesInnerDevice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function GetDeviceActivities200ResponseDeviceActivitiesInnerDeviceToJSON(value?: GetDeviceActivities200ResponseDeviceActivitiesInnerDevice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

