/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetDeviceActivities200ResponseDeviceActivitiesInner } from './GetDeviceActivities200ResponseDeviceActivitiesInner';
import {
    GetDeviceActivities200ResponseDeviceActivitiesInnerFromJSON,
    GetDeviceActivities200ResponseDeviceActivitiesInnerFromJSONTyped,
    GetDeviceActivities200ResponseDeviceActivitiesInnerToJSON,
} from './GetDeviceActivities200ResponseDeviceActivitiesInner';

/**
 * 
 * @export
 * @interface GetDeviceActivities200Response
 */
export interface GetDeviceActivities200Response {
    /**
     * 
     * @type {Array<GetDeviceActivities200ResponseDeviceActivitiesInner>}
     * @memberof GetDeviceActivities200Response
     */
    deviceActivities: Array<GetDeviceActivities200ResponseDeviceActivitiesInner>;
}

/**
 * Check if a given object implements the GetDeviceActivities200Response interface.
 */
export function instanceOfGetDeviceActivities200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "deviceActivities" in value;

    return isInstance;
}

export function GetDeviceActivities200ResponseFromJSON(json: any): GetDeviceActivities200Response {
    return GetDeviceActivities200ResponseFromJSONTyped(json, false);
}

export function GetDeviceActivities200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDeviceActivities200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deviceActivities': ((json['deviceActivities'] as Array<any>).map(GetDeviceActivities200ResponseDeviceActivitiesInnerFromJSON)),
    };
}

export function GetDeviceActivities200ResponseToJSON(value?: GetDeviceActivities200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deviceActivities': ((value.deviceActivities as Array<any>).map(GetDeviceActivities200ResponseDeviceActivitiesInnerToJSON)),
    };
}

