/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetRawAnalytics200ResponseRawAnalyticsDataInner } from './GetRawAnalytics200ResponseRawAnalyticsDataInner';
import {
    GetRawAnalytics200ResponseRawAnalyticsDataInnerFromJSON,
    GetRawAnalytics200ResponseRawAnalyticsDataInnerFromJSONTyped,
    GetRawAnalytics200ResponseRawAnalyticsDataInnerToJSON,
} from './GetRawAnalytics200ResponseRawAnalyticsDataInner';

/**
 * 
 * @export
 * @interface GetRawAnalytics200ResponseRawAnalytics
 */
export interface GetRawAnalytics200ResponseRawAnalytics {
    /**
     * 
     * @type {Array<GetRawAnalytics200ResponseRawAnalyticsDataInner>}
     * @memberof GetRawAnalytics200ResponseRawAnalytics
     */
    data: Array<GetRawAnalytics200ResponseRawAnalyticsDataInner>;
}

/**
 * Check if a given object implements the GetRawAnalytics200ResponseRawAnalytics interface.
 */
export function instanceOfGetRawAnalytics200ResponseRawAnalytics(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetRawAnalytics200ResponseRawAnalyticsFromJSON(json: any): GetRawAnalytics200ResponseRawAnalytics {
    return GetRawAnalytics200ResponseRawAnalyticsFromJSONTyped(json, false);
}

export function GetRawAnalytics200ResponseRawAnalyticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRawAnalytics200ResponseRawAnalytics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetRawAnalytics200ResponseRawAnalyticsDataInnerFromJSON)),
    };
}

export function GetRawAnalytics200ResponseRawAnalyticsToJSON(value?: GetRawAnalytics200ResponseRawAnalytics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetRawAnalytics200ResponseRawAnalyticsDataInnerToJSON)),
    };
}

