/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplaceAutomationActionRequestAction
 */
export interface ReplaceAutomationActionRequestAction {
    /**
     * 
     * @type {number}
     * @memberof ReplaceAutomationActionRequestAction
     */
    device_id: number | null;
    /**
     * 
     * @type {string}
     * @memberof ReplaceAutomationActionRequestAction
     */
    device_state: ReplaceAutomationActionRequestActionDeviceStateEnum;
    /**
     * 
     * @type {number}
     * @memberof ReplaceAutomationActionRequestAction
     */
    device_value: number | null;
}


/**
 * @export
 */
export const ReplaceAutomationActionRequestActionDeviceStateEnum = {
    On: 'on',
    Off: 'off'
} as const;
export type ReplaceAutomationActionRequestActionDeviceStateEnum = typeof ReplaceAutomationActionRequestActionDeviceStateEnum[keyof typeof ReplaceAutomationActionRequestActionDeviceStateEnum];


/**
 * Check if a given object implements the ReplaceAutomationActionRequestAction interface.
 */
export function instanceOfReplaceAutomationActionRequestAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "device_id" in value;
    isInstance = isInstance && "device_state" in value;
    isInstance = isInstance && "device_value" in value;

    return isInstance;
}

export function ReplaceAutomationActionRequestActionFromJSON(json: any): ReplaceAutomationActionRequestAction {
    return ReplaceAutomationActionRequestActionFromJSONTyped(json, false);
}

export function ReplaceAutomationActionRequestActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplaceAutomationActionRequestAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'device_id': json['device_id'],
        'device_state': json['device_state'],
        'device_value': json['device_value'],
    };
}

export function ReplaceAutomationActionRequestActionToJSON(value?: ReplaceAutomationActionRequestAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'device_id': value.device_id,
        'device_state': value.device_state,
        'device_value': value.device_value,
    };
}

