/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplaceAutomationConditionsRequestConditionsInner
 */
export interface ReplaceAutomationConditionsRequestConditionsInner {
    /**
     * 
     * @type {string}
     * @memberof ReplaceAutomationConditionsRequestConditionsInner
     */
    condition_type: ReplaceAutomationConditionsRequestConditionsInnerConditionTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ReplaceAutomationConditionsRequestConditionsInner
     */
    device_id: number | null;
    /**
     * 
     * @type {string}
     * @memberof ReplaceAutomationConditionsRequestConditionsInner
     */
    device_state: ReplaceAutomationConditionsRequestConditionsInnerDeviceStateEnum;
    /**
     * 
     * @type {number}
     * @memberof ReplaceAutomationConditionsRequestConditionsInner
     */
    device_value: number | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ReplaceAutomationConditionsRequestConditionsInner
     */
    device_extra_data: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof ReplaceAutomationConditionsRequestConditionsInner
     */
    cron_expression: string | null;
}


/**
 * @export
 */
export const ReplaceAutomationConditionsRequestConditionsInnerConditionTypeEnum = {
    Device: 'device',
    Cron: 'cron'
} as const;
export type ReplaceAutomationConditionsRequestConditionsInnerConditionTypeEnum = typeof ReplaceAutomationConditionsRequestConditionsInnerConditionTypeEnum[keyof typeof ReplaceAutomationConditionsRequestConditionsInnerConditionTypeEnum];

/**
 * @export
 */
export const ReplaceAutomationConditionsRequestConditionsInnerDeviceStateEnum = {
    On: 'on',
    Off: 'off'
} as const;
export type ReplaceAutomationConditionsRequestConditionsInnerDeviceStateEnum = typeof ReplaceAutomationConditionsRequestConditionsInnerDeviceStateEnum[keyof typeof ReplaceAutomationConditionsRequestConditionsInnerDeviceStateEnum];


/**
 * Check if a given object implements the ReplaceAutomationConditionsRequestConditionsInner interface.
 */
export function instanceOfReplaceAutomationConditionsRequestConditionsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "condition_type" in value;
    isInstance = isInstance && "device_id" in value;
    isInstance = isInstance && "device_state" in value;
    isInstance = isInstance && "device_value" in value;
    isInstance = isInstance && "device_extra_data" in value;
    isInstance = isInstance && "cron_expression" in value;

    return isInstance;
}

export function ReplaceAutomationConditionsRequestConditionsInnerFromJSON(json: any): ReplaceAutomationConditionsRequestConditionsInner {
    return ReplaceAutomationConditionsRequestConditionsInnerFromJSONTyped(json, false);
}

export function ReplaceAutomationConditionsRequestConditionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplaceAutomationConditionsRequestConditionsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'condition_type': json['condition_type'],
        'device_id': json['device_id'],
        'device_state': json['device_state'],
        'device_value': json['device_value'],
        'device_extra_data': json['device_extra_data'],
        'cron_expression': json['cron_expression'],
    };
}

export function ReplaceAutomationConditionsRequestConditionsInnerToJSON(value?: ReplaceAutomationConditionsRequestConditionsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'condition_type': value.condition_type,
        'device_id': value.device_id,
        'device_state': value.device_state,
        'device_value': value.device_value,
        'device_extra_data': value.device_extra_data,
        'cron_expression': value.cron_expression,
    };
}

