/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReplaceAutomationActionRequestAction } from './ReplaceAutomationActionRequestAction';
import {
    ReplaceAutomationActionRequestActionFromJSON,
    ReplaceAutomationActionRequestActionFromJSONTyped,
    ReplaceAutomationActionRequestActionToJSON,
} from './ReplaceAutomationActionRequestAction';

/**
 * 
 * @export
 * @interface ReplaceAutomationActionRequest
 */
export interface ReplaceAutomationActionRequest {
    /**
     * 
     * @type {ReplaceAutomationActionRequestAction}
     * @memberof ReplaceAutomationActionRequest
     */
    action: ReplaceAutomationActionRequestAction;
}

/**
 * Check if a given object implements the ReplaceAutomationActionRequest interface.
 */
export function instanceOfReplaceAutomationActionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;

    return isInstance;
}

export function ReplaceAutomationActionRequestFromJSON(json: any): ReplaceAutomationActionRequest {
    return ReplaceAutomationActionRequestFromJSONTyped(json, false);
}

export function ReplaceAutomationActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplaceAutomationActionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': ReplaceAutomationActionRequestActionFromJSON(json['action']),
    };
}

export function ReplaceAutomationActionRequestToJSON(value?: ReplaceAutomationActionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': ReplaceAutomationActionRequestActionToJSON(value.action),
    };
}

