/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AutomationCondition } from './AutomationCondition';
import {
    AutomationConditionFromJSON,
    AutomationConditionFromJSONTyped,
    AutomationConditionToJSON,
} from './AutomationCondition';

/**
 * 
 * @export
 * @interface ReplaceAutomationConditions200Response
 */
export interface ReplaceAutomationConditions200Response {
    /**
     * 
     * @type {Array<AutomationCondition>}
     * @memberof ReplaceAutomationConditions200Response
     */
    conditions: Array<AutomationCondition>;
}

/**
 * Check if a given object implements the ReplaceAutomationConditions200Response interface.
 */
export function instanceOfReplaceAutomationConditions200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "conditions" in value;

    return isInstance;
}

export function ReplaceAutomationConditions200ResponseFromJSON(json: any): ReplaceAutomationConditions200Response {
    return ReplaceAutomationConditions200ResponseFromJSONTyped(json, false);
}

export function ReplaceAutomationConditions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplaceAutomationConditions200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'conditions': ((json['conditions'] as Array<any>).map(AutomationConditionFromJSON)),
    };
}

export function ReplaceAutomationConditions200ResponseToJSON(value?: ReplaceAutomationConditions200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'conditions': ((value.conditions as Array<any>).map(AutomationConditionToJSON)),
    };
}

