/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAutomationRequest
 */
export interface UpdateAutomationRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateAutomationRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAutomationRequest
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateAutomationRequest
     */
    logical_operator: UpdateAutomationRequestLogicalOperatorEnum;
}


/**
 * @export
 */
export const UpdateAutomationRequestLogicalOperatorEnum = {
    And: 'and',
    Or: 'or'
} as const;
export type UpdateAutomationRequestLogicalOperatorEnum = typeof UpdateAutomationRequestLogicalOperatorEnum[keyof typeof UpdateAutomationRequestLogicalOperatorEnum];


/**
 * Check if a given object implements the UpdateAutomationRequest interface.
 */
export function instanceOfUpdateAutomationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "logical_operator" in value;

    return isInstance;
}

export function UpdateAutomationRequestFromJSON(json: any): UpdateAutomationRequest {
    return UpdateAutomationRequestFromJSONTyped(json, false);
}

export function UpdateAutomationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAutomationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'logical_operator': json['logical_operator'],
    };
}

export function UpdateAutomationRequestToJSON(value?: UpdateAutomationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'logical_operator': value.logical_operator,
    };
}

