/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSignUp200ResponseUser
 */
export interface UserSignUp200ResponseUser {
    /**
     * 
     * @type {number}
     * @memberof UserSignUp200ResponseUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserSignUp200ResponseUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserSignUp200ResponseUser
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserSignUp200ResponseUser
     */
    image_url: string | null;
}

/**
 * Check if a given object implements the UserSignUp200ResponseUser interface.
 */
export function instanceOfUserSignUp200ResponseUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "image_url" in value;

    return isInstance;
}

export function UserSignUp200ResponseUserFromJSON(json: any): UserSignUp200ResponseUser {
    return UserSignUp200ResponseUserFromJSONTyped(json, false);
}

export function UserSignUp200ResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSignUp200ResponseUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'name': json['name'],
        'image_url': json['image_url'],
    };
}

export function UserSignUp200ResponseUserToJSON(value?: UserSignUp200ResponseUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'name': value.name,
        'image_url': value.image_url,
    };
}

