/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserSignUp200ResponseUser } from './UserSignUp200ResponseUser';
import {
    UserSignUp200ResponseUserFromJSON,
    UserSignUp200ResponseUserFromJSONTyped,
    UserSignUp200ResponseUserToJSON,
} from './UserSignUp200ResponseUser';

/**
 * 
 * @export
 * @interface UserSignUp200Response
 */
export interface UserSignUp200Response {
    /**
     * 
     * @type {UserSignUp200ResponseUser}
     * @memberof UserSignUp200Response
     */
    user: UserSignUp200ResponseUser;
}

/**
 * Check if a given object implements the UserSignUp200Response interface.
 */
export function instanceOfUserSignUp200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

export function UserSignUp200ResponseFromJSON(json: any): UserSignUp200Response {
    return UserSignUp200ResponseFromJSONTyped(json, false);
}

export function UserSignUp200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSignUp200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserSignUp200ResponseUserFromJSON(json['user']),
    };
}

export function UserSignUp200ResponseToJSON(value?: UserSignUp200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserSignUp200ResponseUserToJSON(value.user),
    };
}

